# Generated by Django 3.2.9 on 2021-11-25 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custemer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_custemer', models.CharField(blank=True, max_length=50, null=True)),
                ('name_custemer', models.CharField(blank=True, max_length=50, null=True)),
                ('email_custemer', models.CharField(blank=True, max_length=50, null=True)),
                ('telpon_custemer', models.CharField(blank=True, max_length=50, null=True)),
                ('alamat_custemer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Obat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_obat', models.CharField(max_length=50)),
                ('name_obat', models.CharField(max_length=50)),
                ('price_obat', models.IntegerField(blank=True, null=True)),
                ('stok_obat', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('qty_order', models.IntegerField(blank=True, null=True)),
                ('qty_price', models.IntegerField(blank=True, null=True)),
                ('discon', models.IntegerField(blank=True, null=True)),
                ('price_after_disc', models.IntegerField(blank=True, null=True)),
                ('custemer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.custemer')),
                ('obat_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.obat')),
            ],
        ),
    ]
