# Generated by Django 3.2.9 on 2021-11-25 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemer',
            name='email_custemer',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
