# Generated by Django 3.2.9 on 2021-11-25 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_custemer_email_custemer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custemer',
            name='email_custemer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='obat',
            name='description',
            field=models.TextField(),
        ),
    ]
